name: Testing
on: push


jobs:
  test_project:
   runs-on: ubuntu_latest
   steps:
     - uses: actions/checkout@v5
     - name: Run Django unit tests
       run: 
        pip3 install --user django
        python3 manage.py tests